### ISSUE TITLE
Here are two problems in your front end.

### ISSUE THREAD

**Issue by i-forgot-my-name** [yiny0liuyin/yiny0liuyin.github.io#1]
I saw your discussion in ojc's group.

Console returns two errors:

```js
live2d.js: Uncaught SyntaxError: Unexpected token this
message.js:78 Uncaught SyntaxError: Unexpected token =
```

Let's see `message.js` first.

At Line 78, here is obviously an error.

```js
if (now > 23 || now <= 5)="" {="" text="你是夜猫子呀？这么晚还不睡觉，明天起的来嘛？" ;="" }="" else="" if="" (now=""> 5 && now <= 7)="" {="" text="早上好！一日之计在于晨，美好的一天就要开始了！" ;="" }="" else="" if="" (now=""> 7 && now <= 11)="" {="" text="上午好！工作顺利嘛，不要久坐，多起来走动走动哦！" ;="" }="" else="" if="" (now=""> 11 && now <= 14)="" {="" text="中午了，工作了一个上午，现在是午餐时间！" ;="" }="" else="" if="" (now=""> 14 && now <= 17)="" {="" text="午后很容易犯困呢，今天的运动目标完成了吗？" ;="" }="" else="" if="" (now=""> 17 && now <= 19)="" {="" text="傍晚了！窗外夕阳的景色很美丽呢，最美不过夕阳红~~" ;="" }="" else="" if="" (now=""> 19 && now <= 21)="" {="" text="晚上好，今天过得怎么样？" ;="" }="" else="" if="" (now=""> 21 && now <= 23)="" {="" text="已经这么晚了呀，早点休息吧，晚安~~" ;="" }="" else="" }else="" +="" document.title.split('="" -="" ')[0]="" '="" 」<="" span="">';
```

Here are so many isolate `=""` in your code. It's strange!

And my advice is using switch case, it'll make things clearer. Like this:

```js
switch(true){
    case (now>23 || now<=5):
        text='blahblah';
        break;
    case (now>5 || now<=7):
        text='blahblahblah';
        break;
}
```

And another problem is Live2D.js

I tried the latest dist in `galnetwen/Live2D`, seems it won't throw any error. You should download it again and commit it.

[https://raw.githubusercontent.com/galnetwen/Live2D/master/live2d/js/live2d.js](https://raw.githubusercontent.com/galnetwen/Live2D/master/live2d/js/live2d.js)

**Comment by i-forgot-my-name** [comment]
And ALWAYS USE **OFFICIAL** DOCS!

**Comment by Innei** [comment]
Thanks for your advice ,I refer to https://github.com/galnetwen/Live2D, use his demo, but it doesn't seem to work. Yesterday I use too many live2d's api.But they also seem to failed. This is my first build personal blog ,so I do not have much experience. The hexo provides the live2d plugin , I use official docs ,add live2d to theme's ``_config.yml`` ,but when I debug,it didn't show live2d. I don't know where the problem is. Here are my code.
```yaml

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  log: false
  model:
    use: live2d-widget-model-z16
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true 
```
